# Generated by Django 3.2.3 on 2021-06-21 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('IdDelivery', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de delivery')),
                ('NombreServicio', models.CharField(max_length=30, verbose_name='Nombre del servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('RutCliente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='RutCliente')),
                ('Bebida', models.CharField(max_length=25, verbose_name='Bebida')),
                ('Comida', models.CharField(max_length=40, verbose_name='Comida')),
                ('Dirección', models.CharField(max_length=100, verbose_name='Dirección')),
                ('Delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.delivery')),
            ],
        ),
    ]
