# Generated by Django 3.2.4 on 2021-07-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pedido_dirección'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Bebida',
        ),
        migrations.AddField(
            model_name='pedido',
            name='NumeroIdenticacion',
            field=models.CharField(default=5, max_length=25, verbose_name='NumeroIdenticacion'),
            preserve_default=False,
        ),
    ]
