# Generated by Django 3.2.4 on 2021-07-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210707_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Comida',
        ),
        migrations.AddField(
            model_name='pedido',
            name='Nombre',
            field=models.CharField(default=2, max_length=40, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
