# Generated by Django 3.2.4 on 2021-07-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210707_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Delivery',
        ),
        migrations.AddField(
            model_name='pedido',
            name='Telefono',
            field=models.CharField(default=2, max_length=40, verbose_name='Telefono'),
            preserve_default=False,
        ),
    ]
