# Generated by Django 3.2.4 on 2021-07-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210707_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Moneda',
            field=models.CharField(default=2, max_length=40, verbose_name='Moneda'),
            preserve_default=False,
        ),
    ]
