# Generated by Django 3.2.4 on 2021-07-08 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pedido_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Moneda',
        ),
    ]
